//*****************************************************************************
// Module Name : full_adder
// Author      : Abubakar Shuaibu
// Date        : 05 July 2026
// Description :
// This module implements a 1-bit Full Adder using behavioral modeling.
// It adds two 1-bit binary inputs (A and B) together with a carry-in (Cin)
// and produces a sum (Sum) and a carry-out (Cout).
//*****************************************************************************

module full_adder(

    input A, B, Cin,          // Declare the three 1-bit input signals:
                               // A    = First operand
                               // B    = Second operand
                               // Cin  = Carry input from the previous stage

    output reg Sum, Cout       // Declare the outputs as 'reg' because they
                               // are assigned inside an always block.
                               // Sum  = Result of the addition
                               // Cout = Carry output to the next stage
);

// Behavioral block that executes whenever any input changes.
// The (*) automatically includes all signals used inside the block.
always @(*) begin

    // Compute the Sum output.
    // The XOR operation performs binary addition without considering carry generation.
    // Sum is 1 when an odd number of inputs are 1.
    Sum = A ^ B ^ Cin;

    // Compute the Carry-Out output.
    // Carry is generated if any two or more of the three inputs are 1.
    // (A & B)     -> Carry generated by A and B
    // (B & Cin)   -> Carry generated by B and Cin
    // (A & Cin)   -> Carry generated by A and Cin
    Cout = (A & B) | (B & Cin) | (A & Cin);

end

endmodule // End of the full_adder module